
export enum PermissionStatus {
  CHECKING = 'CHECKING',
  GRANTED = 'GRANTED',
  DENIED = 'DENIED',
  BLOQUEO = 'BLOQUEO',
  LIMITED = 'LIMITED',
  UNAVAILABLE = 'UNAVAILABLE',
  UNDETERMINED = 'UNDETERMINED',
}